/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mercado;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class JFMercado extends javax.swing.JFrame {

    /**
     * Creates new form JFMercado
     */
    public JFMercado() {
        initComponents();
        mostrar();
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        TFPreco = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        atuaButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        JBVender = new javax.swing.JButton();
        JBComprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Preco");

        addButton.setText("Adicionar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        atuaButton.setText("Atualizar");
        atuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atuaButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Deletar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        JBVender.setText("Vender");
        JBVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVenderActionPerformed(evt);
            }
        });

        JBComprar.setText("Comprar");
        JBComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBComprarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(JBVender)
                            .addGap(18, 18, 18)
                            .addComponent(JBComprar)
                            .addGap(448, 448, 448))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(63, 63, 63)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFnome, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(TFPreco)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(addButton)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atuaButton)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(addButton)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(atuaButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBVender)
                    .addComponent(JBComprar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        criar();
    }//GEN-LAST:event_addButtonActionPerformed

    private void atuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atuaButtonActionPerformed
        // TODO add your handling code here:
        atualizar();
    }//GEN-LAST:event_atuaButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void JBVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVenderActionPerformed
        // TODO add your handling code here:
        JFVenda venda = new JFVenda();
        venda.setVisible(true);
    }//GEN-LAST:event_JBVenderActionPerformed

    private void JBComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBComprarActionPerformed
        // TODO add your handling code here:
        JFCompra compra = new JFCompra();
        compra.setVisible(true);
    }//GEN-LAST:event_JBComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBComprar;
    private javax.swing.JButton JBVender;
    private javax.swing.JTextField TFPreco;
    private javax.swing.JTextField TFnome;
    private javax.swing.JButton addButton;
    private javax.swing.JButton atuaButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void criar() {
        Random random = new Random();
        int id = random.nextInt(1000) + 1;
        id = idEquivalente(id);
                
        String nome = TFnome.getText();
        double preco = Double.parseDouble(TFPreco.getText());
        int qtd = 0;
        
        
        Produto p = new Produto(id, nome, preco, qtd);
        ProdutoCRUD pr = new ProdutoCRUD("arq.txt");
        
        pr.adicionarProduto(p);
        
        mostrar();
        limpa();
    }
    
    private int idEquivalente(int id){
        ProdutoCRUD pr = new ProdutoCRUD("arq.txt");
        List<Produto> produtos = pr.lerProdutos();
        
        for (Produto produto : produtos ){
            if (produto.getId() == id){
                System.out.println(id);
                Random random = new Random();
                id = random.nextInt(1000) + 1;
                System.out.println(id);
                return idEquivalente(id);
            }
        }
        return id;
    }
    
    private void mostrar(){
        ProdutoCRUD crud = new ProdutoCRUD("arq.txt");
        List<Produto> listP = crud.lerProdutos();
        
        String[] colunas = {"ID", "Nome", "Preço", "Quantidade"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        

        
        jTable1.setModel(modelo);
        
        
        for (Produto produto : listP) {
            Object[] linha = {
                produto.getId(),
                produto.getNome(),
                produto.getPreco(),
                produto.getQuantidade()
            };
            
            modelo.addRow(linha);
        }
    }

    private void atualizar() {
        
        String valor = "";
        String nome = "";
        int id = 0;
        JTextField idField = new JTextField();
        JTextField nomeField = new JTextField();
        JTextField valorField = new JTextField();
        
        
        // Cria um painel para organizar os componentes
        JPanel painel = new JPanel(new GridLayout(3, 3));
        painel.add(new JLabel("Digite o ID do produto"));
        painel.add(idField);
        painel.add(new JLabel("O novo nome do seu produto:"));
        painel.add(nomeField);
        painel.add(new JLabel("Digite o novo valor do produto:"));
        painel.add(valorField);

        // Exibe o painel em um JOptionPane
        int resultado = JOptionPane.showConfirmDialog(null, painel, 
                "Informações Pessoais", JOptionPane.OK_CANCEL_OPTION);

        // Verifica se o usuário clicou em OK
        if (resultado == JOptionPane.OK_OPTION) {
            String strid = idField.getText();
            nome = nomeField.getText();
            valor = valorField.getText();
            
            id = Integer.parseInt(strid);
        } else {
            System.out.println("Operação cancelada.");
        }
        
        
        
        ProdutoCRUD pr = new ProdutoCRUD("arq.txt");
        List<Produto> produtos = pr.lerProdutos();
        Produto p2 = new Produto(0, "0", 0, 0);
        
        for(Produto p: produtos){
            if(id != 0){
                if(p.getId() == id){
                p2 = p;
                }
            } 
        }
        
        if(!"".equals(nome)){
            p2.setNome(nome);
        } 
        
        if(!"".equals(valor)){
            p2.setPreco(Double.parseDouble(valor));
        }
        

        pr.atualizarProduto(id, p2);
        
        mostrar();
        limpa();
    }
    
    

    private void excluir() {
        
        int id = 0;
        
        JTextField idField = new JTextField();
        
        JPanel painel = new JPanel(new GridLayout(3, 3));
        painel.add(new JLabel("Digite o ID do produto"));
        painel.add(idField);
        
        int resultado = JOptionPane.showConfirmDialog(null, painel, 
                "Informações Pessoais", JOptionPane.OK_CANCEL_OPTION);
        
        if (resultado == JOptionPane.OK_OPTION) {
            String strid = idField.getText();
            
            
            id = Integer.parseInt(strid);
        } else {
            System.out.println("Operação cancelada.");
        }
        
        
        ProdutoCRUD pr = new ProdutoCRUD("arq.txt");
        
        
        
        if(id != 0){
            pr.excluirProduto(id);
        }
        
        
        mostrar();
        limpa();
    }
    
    private void limpa(){
        TFnome.setText("");
        TFPreco.setText("");
    }
    
    
}
